name: Deploy to Render
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4lbj249c44c73fdtjn0?key=GIIhRwMqsjE
          
